apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
        - name: student-management
          image: dalirom123/student-management:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8089   # ✅ PORT CORRECT

          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"

            # ✅ DÉSACTIVE COMPLÈTEMENT MYSQL / JPA
            - name: SPRING_AUTOCONFIGURE_EXCLUDE
              value: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
